// <auto-generated/>
#pragma warning disable
#nullable enable annotations

#pragma warning disable CS0612
#pragma warning disable CS0618
#pragma warning disable CS0108
#pragma warning disable CS0162
#pragma warning disable CS0164
#pragma warning disable CS0219
#pragma warning disable CS8602
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631
#pragma warning disable CA1050

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Diagnostics.CodeAnalysis;

/// <summary>
/// Specifies that an output will not be null even if the corresponding type allows it.
/// Specifies that an input argument was not null when the call returns.
/// </summary>
[global::System.AttributeUsage(
    global::System.AttributeTargets.Field |
    global::System.AttributeTargets.Parameter |
    global::System.AttributeTargets.Property |
    global::System.AttributeTargets.ReturnValue,
    Inherited = false)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
internal sealed class NotNullAttribute : global::System.Attribute;
