using System.Diagnostics;
using System.Text;

namespace Nogic.ThrowHelperExtensions;

/// <summary>
/// Builds ExceptionPolyfills source code dynamically based on target framework.
/// </summary>
internal static class ExceptionPolyfillsBuilder
{
    /// <summary>
    /// Generates the ExceptionPolyfills source code for the specified target framework.
    /// </summary>
    /// <param name="targetFramework">The target framework version.</param>
    /// <param name="includeUnsafe">Whether to include unsafe variants.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Generate(TargetFramework targetFramework, bool includeUnsafe)
    {
        // Estimated buffer size based on minimum output (.NET 8+ with no unsafe):
        // - Header + class declaration: ~800 bytes
        // Rounded up to 1KB for safety margin
        var builder = new StringBuilder(capacity: 1024);

        // Header
        // lang=c#-test
        builder.AppendLine("""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations
        
        #pragma warning disable CS0612
        #pragma warning disable CS0618
        #pragma warning disable CS0108
        #pragma warning disable CS0162
        #pragma warning disable CS0164
        #pragma warning disable CS0219
        #pragma warning disable CS8602
        #pragma warning disable CS8619
        #pragma warning disable CS8620
        #pragma warning disable CS8631
        #pragma warning disable CA1050

        // Licensed to the .NET Foundation under one or more agreements.
        // The .NET Foundation licenses this file to you under the MIT license.

        namespace System;

        """);

        // lang=c#-test
        builder.AppendLine("""
        /// <summary>Provides downlevel polyfills for static methods on Exception-derived types.</summary>
        [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
        internal static partial class ExceptionPolyfills
        {
        """);

        GenerateArgumentNullException(builder, targetFramework, includeUnsafe);
        GenerateArgumentException(builder, targetFramework);
        GenerateObjectDisposedException(builder, targetFramework);
        GenerateArgumentOutOfRangeException(builder, targetFramework);

        // lang=c#-test
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GenerateArgumentNullException(StringBuilder builder, TargetFramework targetFramework, bool includeUnsafe)
    {
        // ArgumentNullException.ThrowIfNull(object) is available in .NET 6+
        // ArgumentNullException.ThrowIfNull(void*) is available in .NET 7+
        bool hasSafeVariant = targetFramework < TargetFramework.Net6;
        bool hasUnsafeVariant = includeUnsafe && targetFramework < TargetFramework.Net7;

        if (!hasSafeVariant && !hasUnsafeVariant)
            return;

        // lang=c#-test
        builder.Append("""
            /// <summary>Extension for <see cref="global::System.ArgumentNullException"/>.</summary>
            extension(global::System.ArgumentNullException)
            {
        """);

        // Generate safe variant for .NET 6.0 and earlier
        if (hasSafeVariant)
        {
            // lang=c#-test
            builder.AppendLine("""
                    /// <summary>
                    /// Throws an <see cref="global::System.ArgumentNullException"/> if <paramref name="argument"/> is <see langword="null"/>.
                    /// </summary>
                    /// <param name="argument">The reference type argument to validate as non-null.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentNullException"><paramref name="argument"/> is <see langword="null"/>.</exception>
                    public static void ThrowIfNull(
                        [global::System.Diagnostics.CodeAnalysis.NotNull] object? argument,
                        [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(argument))] string? paramName = null
                    )
                    {
                        if (argument is null)
                            ThrowArgumentNullException(paramName);
                    }
            """);
        }

        // Generate unsafe variant for .NET 7.0 and earlier when unsafe is enabled
        if (hasUnsafeVariant)
        {
            // lang=c#-test
            builder.AppendLine("""
                    /// <summary>
                    /// Throws an <see cref="global::System.ArgumentNullException"/> if <paramref name="argument"/> is <see langword="null"/>.
                    /// </summary>
                    /// <param name="argument">The pointer argument to validate as non-null.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentNullException"><paramref name="argument"/> is <see langword="null"/>.</exception>
                    [global::System.CLSCompliant(false)]
                    public unsafe static void ThrowIfNull(
                        [global::System.Diagnostics.CodeAnalysis.NotNull] void* argument,
                        [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(argument))] string? paramName = null
                    )
                    {
                        if (argument is null)
                            ThrowArgumentNullException(paramName);
                    }
            """);
        }

        // Helper method (shared between safe and unsafe variants)
        // lang=c#-test
        builder.AppendLine("""
                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowArgumentNullException(string? paramName)
                    => throw new global::System.ArgumentNullException(paramName);
            }
        """);
    }

    private static void GenerateArgumentException(StringBuilder builder, TargetFramework targetFramework)
    {
        if (targetFramework >= TargetFramework.Net8OrGreater)
            return;

        // ThrowIfNullOrEmpty is available in .NET 7+
        // ThrowIfNullOrWhiteSpace is available in .NET 8+
        bool includeThrowIfNullOrEmpty = targetFramework < TargetFramework.Net7;

        // lang=c#-test
        builder.AppendLine("""
            /// <summary>
            /// Extension for <see cref="global::System.ArgumentException"/>.
            /// </summary>
            extension(global::System.ArgumentException)
            {
        """);

        if (includeThrowIfNullOrEmpty)
        {
            // lang=c#-test
            builder.AppendLine("""
                    /// <summary>Throws an exception if <paramref name="argument"/> is <see langword="null"/> or empty.</summary>
                    /// <param name="argument">The string argument to validate as non-null and non-empty.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentNullException"><paramref name="argument"/> is <see langword="null"/>.</exception>
                    /// <exception cref="global::System.ArgumentException"><paramref name="argument"/> is empty.</exception>
                    public static void ThrowIfNullOrEmpty(
                        [global::System.Diagnostics.CodeAnalysis.NotNull] string? argument,
                        [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(argument))] string? paramName = null
                    )
                    {
                        if (string.IsNullOrEmpty(argument))
                            ThrowArgumentException(argument, paramName, "Value cannot be an empty string.");
                    }
            """);
        }

        // lang=c#-test
        builder.AppendLine("""
                /// <summary>Throws an exception if <paramref name="argument"/> is null, empty, or consists only of white-space characters.</summary>
                /// <param name="argument">The string argument to validate.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="argument"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentNullException"><paramref name="argument"/> is <see langword="null"/>.</exception>
                /// <exception cref="global::System.ArgumentException"><paramref name="argument"/> is empty or consists only of white-space characters.</exception>
                public static void ThrowIfNullOrWhiteSpace(
                    [global::System.Diagnostics.CodeAnalysis.NotNull] string? argument,
                    [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(argument))] string? paramName = null
                )
                {
                    if (string.IsNullOrWhiteSpace(argument))
                        ThrowArgumentException(argument, paramName, "The value cannot be an empty string or composed entirely of whitespace.");
                }
        """);

        // lang=c#-test
        builder.AppendLine("""
                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowArgumentException(string? argument, string? paramName, string message)
                {
                    global::System.ArgumentNullException.ThrowIfNull(argument, paramName);
                    throw new global::System.ArgumentException(message, paramName);
                }
            }
        """);
    }

    private static void GenerateObjectDisposedException(StringBuilder builder, TargetFramework targetFramework)
    {
        // ObjectDisposedException.ThrowIf is available in .NET 7+
        if (targetFramework >= TargetFramework.Net7)
            return;

        // lang=c#-test
        builder.AppendLine("""
                /// <summary>
                /// Extension for <see cref="global::System.ObjectDisposedException"/>.
                /// </summary>
                extension(global::System.ObjectDisposedException)
                {
                    /// <summary>Throws an <see cref="global::System.ObjectDisposedException"/> if the specified <paramref name="condition"/> is <see langword="true"/>.</summary>
                    /// <param name="condition">The condition to evaluate.</param>
                    /// <param name="instance">The object whose type's full name should be included in any resulting <see cref="global::System.ObjectDisposedException"/>.</param>
                    /// <exception cref="global::System.ObjectDisposedException">The <paramref name="condition"/> is <see langword="true"/>.</exception>
                    public static void ThrowIf([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIf(true)] bool condition, object instance)
                    {
                        if (condition)
                            ThrowObjectDisposedException(instance.GetType());
                    }

                    /// <summary>Throws an <see cref="global::System.ObjectDisposedException"/> if the specified <paramref name="condition"/> is <see langword="true"/>.</summary>
                    /// <param name="condition">The condition to evaluate.</param>
                    /// <param name="type">The type whose full name should be included in any resulting <see cref="global::System.ObjectDisposedException"/>.</param>
                    /// <exception cref="global::System.ObjectDisposedException">The <paramref name="condition"/> is <see langword="true"/>.</exception>
                    public static void ThrowIf([global::System.Diagnostics.CodeAnalysis.DoesNotReturnIf(true)] bool condition, global::System.Type type)
                    {
                        if (condition)
                            ThrowObjectDisposedException(type);
                    }

                    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                    private static void ThrowObjectDisposedException(global::System.Type type)
                        => throw new global::System.ObjectDisposedException(type.FullName);
                }
            """);
    }

    private static void GenerateArgumentOutOfRangeException(StringBuilder builder, TargetFramework targetFramework)
    {
        if (targetFramework >= TargetFramework.Net8OrGreater)
            return;

        builder.AppendLine("""
            /// <summary>
            /// Extension for <see cref="global::System.ArgumentOutOfRangeException"/>.
            /// </summary>
            extension(global::System.ArgumentOutOfRangeException)
            {
                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is equal to <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as not equal to <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is equal to <paramref name="other"/>.</exception>
                public static void ThrowIfEqual<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                {
                    if (global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(value, other))
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must not be equal to '{other}'.");
                }

                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is not equal to <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as equal to <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is not equal to <paramref name="other"/>.</exception>
                public static void ThrowIfNotEqual<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                {
                    if (!global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(value, other))
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must be equal to '{other}'.");
                }
        """);

        // Comparison methods
        builder.AppendLine("""
                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is greater than <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as less or equal than <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is greater than <paramref name="other"/>.</exception>
                public static void ThrowIfGreaterThan<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                    where T : global::System.IComparable<T>
                {
                    if (value.CompareTo(other) > 0)
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must be less than or equal to '{other}'.");
                }

                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is greater than or equal <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as less than <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is greater than or equal to <paramref name="other"/>.</exception>
                public static void ThrowIfGreaterThanOrEqual<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                    where T : global::System.IComparable<T>
                {
                    if (value.CompareTo(other) >= 0)
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must be less than '{other}'.");
                }

                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is less than <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as greater than or equal than <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is less than <paramref name="other"/>.</exception>
                public static void ThrowIfLessThan<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                    where T : global::System.IComparable<T>
                {
                    if (value.CompareTo(other) < 0)
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must be greater than or equal to '{other}'.");
                }

                /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is less than or equal <paramref name="other"/>.</summary>
                /// <param name="value">The argument to validate as greater than <paramref name="other"/>.</param>
                /// <param name="other">The value to compare with <paramref name="value"/>.</param>
                /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is less than or equal to <paramref name="other"/>.</exception>
                public static void ThrowIfLessThanOrEqual<T>(T value, T other, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                    where T : global::System.IComparable<T>
                {
                    if (value.CompareTo(other) <= 0)
                        ThrowArgumentOutOfRangeException(value, paramName, $"{paramName} ('{value}') must be greater than '{other}'.");
                }
        """);

        // Numeric methods
        GenerateNumericMethods(builder, targetFramework);

        // Helper methods
        // lang=c#-test
        builder.AppendLine("""
                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowArgumentOutOfRangeException<T>(T value, string? paramName, string message)
                    => throw new global::System.ArgumentOutOfRangeException(paramName, value, message);

                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowZero<T>(T value, string? paramName)
                    => throw new global::System.ArgumentOutOfRangeException(paramName, value, $"{paramName} ('{value}') must be a non-zero value.");

                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowNegative<T>(T value, string? paramName)
                    => throw new global::System.ArgumentOutOfRangeException(paramName, value, $"{paramName} ('{value}') must be a non-negative value.");

                [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
                private static void ThrowNegativeOrZero<T>(T value, string? paramName)
                    => throw new global::System.ArgumentOutOfRangeException(paramName, value, $"{paramName} ('{value}') must be a non-negative and non-zero value.");
            }
        """);
    }

    private static void GenerateNumericMethods(StringBuilder builder, TargetFramework targetFramework)
    {
        Debug.Assert(targetFramework < TargetFramework.Net8OrGreater);

        if (targetFramework == TargetFramework.Net7)
        {
            // INumberBase<T> based overloads for .NET 7
            // lang=c#-test
            builder.AppendLine("""
                    /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is zero.</summary>
                    /// <param name="value">The argument to validate as non-zero.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is zero.</exception>
                    public static void ThrowIfZero<T>(T value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        where T : global::System.Numerics.INumberBase<T>
                    {
                        if (T.IsZero(value))
                            ThrowZero(value, paramName);
                    }

                    /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is negative.</summary>
                    /// <param name="value">The argument to validate as non-negative.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is negative.</exception>
                    public static void ThrowIfNegative<T>(T value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        where T : global::System.Numerics.INumberBase<T>
                    {
                        if (T.IsNegative(value))
                            ThrowNegative(value, paramName);
                    }

                    /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is negative or zero.</summary>
                    /// <param name="value">The argument to validate as non-zero or non-negative.</param>
                    /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                    /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is negative or zero.</exception>
                    public static void ThrowIfNegativeOrZero<T>(T value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        where T : global::System.Numerics.INumberBase<T>
                    {
                        if (T.IsNegative(value) || T.IsZero(value))
                            ThrowNegativeOrZero(value, paramName);
                    }
            """);
        }
        else
        {
            // Primitive numeric type overloads for .NET 6 and earlier
            GeneratePrimitiveTypeOverloads(builder);
        }
    }

    private static void GeneratePrimitiveTypeOverloads(StringBuilder builder)
    {
        (string typeName, bool isClsCompliant, bool hasNegative)[] types =
        [
            ("byte", true, false),
            ("sbyte", false, true),
            ("short", true, true),
            ("ushort", false, false),
            ("int", true, true),
            ("uint", false, false),
            ("long", true, true),
            ("ulong", false, false),
            ("float", true, true),
            ("double", true, true),
            ("decimal", true, true),
            ("nint", true, true),
            ("nuint", false, false),
            ("char", true, false)
        ];

        foreach (var (typeName, isClsCompliant, hasNegative) in types)
        {
            string clsCompliantAttribute = isClsCompliant ? "" : "[global::System.CLSCompliant(false)]";

            // ThrowIfZero
            builder.AppendLine($$"""
                        /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is zero.</summary>
                        /// <param name="value">The argument to validate as non-zero.</param>
                        /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                        /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is zero.</exception>
                        {{clsCompliantAttribute}}
                        public static void ThrowIfZero({{typeName}} value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        {
                            if (value == 0)
                                ThrowZero(value, paramName);
                        }
                """);

            if (hasNegative)
            {
                // ThrowIfNegative
                builder.AppendLine($$"""
                        /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is negative.</summary>
                        /// <param name="value">The argument to validate as non-negative.</param>
                        /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                        /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is negative.</exception>
                        {{clsCompliantAttribute}}
                        public static void ThrowIfNegative({{typeName}} value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        {
                            if (value < 0)
                                ThrowNegative(value, paramName);
                        }
                """);

                // ThrowIfNegativeOrZero
                builder.AppendLine($$"""
                        /// <summary>Throws an <see cref="global::System.ArgumentOutOfRangeException"/> if <paramref name="value"/> is negative or zero.</summary>
                        /// <param name="value">The argument to validate as non-zero or non-negative.</param>
                        /// <param name="paramName">The name of the parameter with which <paramref name="value"/> corresponds.</param>
                        /// <exception cref="global::System.ArgumentOutOfRangeException"><paramref name="value"/> is negative or zero.</exception>
                        {{clsCompliantAttribute}}
                        public static void ThrowIfNegativeOrZero({{typeName}} value, [global::System.Runtime.CompilerServices.CallerArgumentExpression(nameof(value))] string? paramName = null)
                        {
                            if (value <= 0)
                                ThrowNegativeOrZero(value, paramName);
                        }
                """);
            }
        }
    }
}
