namespace Nogic.ThrowHelperExtensions.SourceGenerator.Tests;

/// <summary>
/// Tests for <see cref="ExceptionPolyfillsBuilder"/>.
/// </summary>
public sealed class ExceptionPolyfillsBuilderTests
{
    private const string Generate =
        $"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}";

    public static IEnumerable<
        TestDataRow<(TargetFramework, bool, string[] expected, string[] unexpected)>
    > TestData
    {
        get
        {
            string[] header =
            [
                "// <auto-generated/>",
                "#pragma warning disable",
                "namespace System;",
                "internal static partial class ExceptionPolyfills",
            ];
            const string argumentNullException = "extension(global::System.ArgumentNullException)";
            string[] throwIfNull = ["public static void ThrowIfNull("];
            string[] unsafeCode = ["public unsafe static void ThrowIfNull", "void* argument"];
            const string throwIfEmpty = "public static void ThrowIfNullOrEmpty(";
            string[] throwIfWhiteSpace =
            [
                "extension(global::System.ArgumentException)",
                "public static void ThrowIfNullOrWhiteSpace(",
            ];
            string[] throwIfComparable =
            [
                "extension(global::System.ArgumentOutOfRangeException)",
                "public static void ThrowIfEqual<T>(",
                "public static void ThrowIfNotEqual<T>(",
                "public static void ThrowIfGreaterThan<T>(",
                "public static void ThrowIfLessThan<T>(",
                "public static void ThrowIfGreaterThanOrEqual<T>(",
                "public static void ThrowIfLessThanOrEqual<T>(",
            ];
            string[] throwIfBuiltInNumber =
            [
                "public static void ThrowIfZero(byte value",
                "public static void ThrowIfZero(int value",
                "public static void ThrowIfNegative(int value",
                "public static void ThrowIfNegativeOrZero(int value",
            ];
            string[] throwIfNumberBase =
            [
                "INumberBase<T>",
                "public static void ThrowIfZero<T>(T value",
                "public static void ThrowIfNegative<T>(T value",
                "public static void ThrowIfNegativeOrZero<T>(T value",
            ];
            string[] objectDisposed =
            [
                "extension(global::System.ObjectDisposedException)",
                "public static void ThrowIf(",
            ];

            yield return new(
                (
                    TargetFramework.PreNet6,
                    false,
                    [
                        .. header,
                        argumentNullException,
                        .. throwIfNull,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ],
                    [.. unsafeCode, .. throwIfNumberBase]
                )
            );
            yield return new(
                (
                    TargetFramework.PreNet6,
                    true,
                    [
                        .. header,
                        argumentNullException,
                        .. throwIfNull,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ],
                    [.. throwIfNumberBase]
                )
            );
            yield return new(
                (
                    TargetFramework.Net6,
                    false,
                    [
                        .. header,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ],
                    [.. throwIfNull, .. unsafeCode, .. throwIfNumberBase]
                )
            );
            yield return new(
                (
                    TargetFramework.Net6,
                    true,
                    [
                        .. header,
                        argumentNullException,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ],
                    [.. throwIfNull, .. throwIfNumberBase]
                )
            );
            yield return new(
                (
                    TargetFramework.Net7,
                    false,
                    [.. header, .. throwIfWhiteSpace, .. throwIfComparable, .. throwIfNumberBase],
                    [
                        .. throwIfNull,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ]
                )
            );
            yield return new(
                (
                    TargetFramework.Net7,
                    true,
                    [.. header, .. throwIfWhiteSpace, .. throwIfComparable, .. throwIfNumberBase],
                    [
                        .. throwIfNull,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfBuiltInNumber,
                        .. objectDisposed,
                    ]
                )
            );
            yield return new(
                (
                    TargetFramework.Net8OrGreater,
                    false,
                    [.. header],
                    [
                        .. throwIfNull,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. throwIfNumberBase,
                        .. objectDisposed,
                    ]
                )
            );
            yield return new(
                (
                    TargetFramework.Net8OrGreater,
                    true,
                    [.. header],
                    [
                        .. throwIfNull,
                        .. unsafeCode,
                        throwIfEmpty,
                        .. throwIfWhiteSpace,
                        .. throwIfComparable,
                        .. throwIfBuiltInNumber,
                        .. throwIfNumberBase,
                        .. objectDisposed,
                    ]
                )
            );
        }
    }

    [Test]
    [DisplayName($"{Generate}($targetFramework, $includeUnsafe) > generates expected polyfills")]
    [MethodDataSource(nameof(TestData))]
    public async ValueTask Generate_Includes_Expected_Polyfills(
        TargetFramework targetFramework,
        bool includeUnsafe,
        string[] expected,
        string[] unexpected
    )
    {
        string res = ExceptionPolyfillsBuilder.Generate(targetFramework, includeUnsafe);

        using var _ = Assert.Multiple();
        foreach (string line in expected)
            await Assert.That(res).Contains(line);
        foreach (string line in unexpected)
            await Assert.That(res).DoesNotContain(line);
    }
}
