namespace Nogic.ThrowHelperExtensions.SourceGenerator.Tests;

/// <summary>
/// Tests for <see cref="ExceptionPolyfillsBuilder"/>.
/// </summary>
[TestClass]
public sealed class ExceptionPolyfillsBuilderTests
{
    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(<any>, <any>) > includes header, namespace and class declaration")]
    [DataRow(TargetFramework.PreNet6)]
    [DataRow(TargetFramework.Net6)]
    [DataRow(TargetFramework.Net7)]
    [DataRow(TargetFramework.Net8OrGreater)]
    public void Generate_Includes_Header_And_Namespace(TargetFramework targetFramework)
    {
        // Act
        string result = ExceptionPolyfillsBuilder.Generate(targetFramework, true);

        // Assert
        result.ShouldContain("// <auto-generated/>");
        result.ShouldContain("#pragma warning disable");
        result.ShouldContain("namespace System;");
        result.ShouldContain("internal static partial class ExceptionPolyfills");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(PreNet6, <any>) > generates all polyfills")]
    public void Generate_PreNet6_Includes_All_Polyfills()
    {
        // Act
        string result = ExceptionPolyfillsBuilder.Generate(TargetFramework.PreNet6, false);

        // Assert - ArgumentNullException
        result.ShouldContain("extension(global::System.ArgumentNullException)");
        result.ShouldContain("public static void ThrowIfNull(");

        // Assert - ArgumentException
        result.ShouldContain("extension(global::System.ArgumentException)");
        result.ShouldContain("public static void ThrowIfNullOrEmpty(");
        result.ShouldContain("public static void ThrowIfNullOrWhiteSpace(");

        // Assert - ObjectDisposedException
        result.ShouldContain("extension(global::System.ObjectDisposedException)");
        result.ShouldContain("public static void ThrowIf(");

        // Assert - ArgumentOutOfRangeException
        result.ShouldContain("extension(global::System.ArgumentOutOfRangeException)");
        result.ShouldContain("public static void ThrowIfEqual<T>(");
        result.ShouldContain("public static void ThrowIfNotEqual<T>(");
        result.ShouldContain("public static void ThrowIfGreaterThan<T>(");
        result.ShouldContain("public static void ThrowIfLessThan<T>(");
        // Assert - Should have primitive type overloads for numeric methods
        result.ShouldContain("public static void ThrowIfZero(byte value");
        result.ShouldContain("public static void ThrowIfZero(int value");
        result.ShouldContain("public static void ThrowIfNegative(int value");
        result.ShouldContain("public static void ThrowIfNegativeOrZero(int value");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(Net6, <any>) > generates expected polyfills")]
    public void Generate_Net6_Includes_Expected_Polyfills()
    {
        // Act
        string result = ExceptionPolyfillsBuilder.Generate(TargetFramework.Net6, false);

        // Assert - ArgumentNullException.ThrowIfNull should NOT be included in Net6 or greater
        result.ShouldNotContain("extension(global::System.ArgumentNullException)");

        // Assert - ArgumentException
        result.ShouldContain("extension(global::System.ArgumentException)");
        result.ShouldContain("public static void ThrowIfNullOrEmpty(");
        result.ShouldContain("public static void ThrowIfNullOrWhiteSpace(");

        // Assert - ObjectDisposedException
        result.ShouldContain("extension(global::System.ObjectDisposedException)");
        result.ShouldContain("public static void ThrowIf(");

        // Assert - ArgumentOutOfRangeException
        result.ShouldContain("extension(global::System.ArgumentOutOfRangeException)");
        result.ShouldContain("public static void ThrowIfEqual<T>(");
        result.ShouldContain("public static void ThrowIfNotEqual<T>(");
        result.ShouldContain("public static void ThrowIfGreaterThan<T>(");
        result.ShouldContain("public static void ThrowIfLessThan<T>(");
        // Assert - Should have primitive type overloads for numeric methods
        result.ShouldContain("public static void ThrowIfZero(byte value");
        result.ShouldContain("public static void ThrowIfZero(int value");
        result.ShouldContain("public static void ThrowIfNegative(int value");
        result.ShouldContain("public static void ThrowIfNegativeOrZero(int value");
        // Assert - Should NOT have INumberBase<T> generic version
        result.ShouldNotContain("INumberBase<T>");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(Net7, <any>) > generates expected polyfills")]
    public void Generate_Net7_Includes_Expected_Polyfills()
    {
        // Act
        string result = ExceptionPolyfillsBuilder.Generate(TargetFramework.Net7, false);

        // Assert - ArgumentNullException.ThrowIfNull should NOT be included in Net6 or greater
        result.ShouldNotContain("extension(global::System.ArgumentNullException)");

        // Assert - ArgumentException.ThrowIfNullOrEmpty should NOT be included in Net7 or greater
        result.ShouldContain("extension(global::System.ArgumentException)");
        result.ShouldNotContain("public static void ThrowIfNullOrEmpty(");
        result.ShouldContain("public static void ThrowIfNullOrWhiteSpace(");

        // Assert - ObjectDisposedException.ThrowIf should NOT be included in Net7 or greater
        result.ShouldNotContain("extension(global::System.ObjectDisposedException)");

        // Assert - ArgumentOutOfRangeException
        result.ShouldContain("extension(global::System.ArgumentOutOfRangeException)");
        result.ShouldContain("public static void ThrowIfEqual<T>(");
        result.ShouldContain("public static void ThrowIfNotEqual<T>(");
        result.ShouldContain("public static void ThrowIfGreaterThan<T>(");
        result.ShouldContain("public static void ThrowIfLessThan<T>(");
        // Assert - Should have INumberBase<T> generic versions
        result.ShouldContain("INumberBase<T>");
        result.ShouldContain("public static void ThrowIfZero<T>(T value");
        result.ShouldContain("public static void ThrowIfNegative<T>(T value");
        result.ShouldContain("public static void ThrowIfNegativeOrZero<T>(T value");
        // Assert - Should NOT have primitive type overloads
        result.ShouldNotContain("public static void ThrowIfZero(byte value");
        result.ShouldNotContain("public static void ThrowIfZero(int value");
        result.ShouldNotContain("public static void ThrowIfNegative(int value");
        result.ShouldNotContain("public static void ThrowIfNegativeOrZero(int value");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(Net8OrGreater, <any>) > generates no polyfills")]
    public void Generate_Net8OrGreater_Excludes_All_Polyfills()
    {
        // Arrange - Act
        string result = ExceptionPolyfillsBuilder.Generate(TargetFramework.Net8OrGreater, false);

        // Assert
        result.ShouldNotContain("extension(global::System.ArgumentNullException)");
        result.ShouldNotContain("extension(global::System.ArgumentException)");
        result.ShouldNotContain("extension(global::System.ObjectDisposedException)");
        result.ShouldNotContain("extension(global::System.ArgumentOutOfRangeException)");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(<any>, true) > generates unsafe polyfills")]
    [DataRow(TargetFramework.PreNet6, true)]
    [DataRow(TargetFramework.Net6, true)]
    public void Generate_Unsafe_Code_When(TargetFramework targetFramework, bool allowUnsafe)
    {
        // Act
        string result = ExceptionPolyfillsBuilder.Generate(targetFramework, allowUnsafe);

        // Assert
        result.ShouldContain("public unsafe static void ThrowIfNull");
        result.ShouldContain("void* argument");
    }

    [TestMethod($"{nameof(ExceptionPolyfillsBuilder)}.{nameof(ExceptionPolyfillsBuilder.Generate)}(<any>, false) > does not generate unsafe polyfills")]
    [DataRow(TargetFramework.PreNet6, false)]
    [DataRow(TargetFramework.Net6, false)]
    [DataRow(TargetFramework.Net7, true)]
    [DataRow(TargetFramework.Net8OrGreater, true)]
    public void Does_Not_Include_Unsafe_When(TargetFramework targetFramework, bool allowUnsafe)
    {
        // Arrange - Act
        string result = ExceptionPolyfillsBuilder.Generate(targetFramework, allowUnsafe);

        // Assert
        result.ShouldNotContain("public unsafe static void ThrowIfNull");
        result.ShouldNotContain("void* argument");
    }
}
